upgrade Makefile

diff --git a/test/Makefile b/test/Makefile
--- a/test/Makefile
+++ b/test/Makefile
@@ -1,4 +1,7 @@
-test: $(patsubst %.in,%,$(wildcard test/*.in))
+test: test_clean $(patsubst %.in,%,$(wildcard test/*.in))
+
+test_clean:
+	$(foreach F,$(wildcard test/*.diff),$(shell rm $F))
 
 test/%.tmp: test/%.in
 	$(eval									\
@@ -15,9 +18,22 @@ test/%.tmp: test/%.in
 LABEL_PASS="\033[1;32m[PASSING]\033[1;0m\033[1;2m"
 LABEL_FAIL="\033[1;31m[FAILING]\033[1;0m\033[1;2m"
 
+define test_report
+	@tput sgr 0; tput bold;
+	@if [ $1 == 0 ]; then					\
+		tput setaf 10; printf "[PASSING]";	\
+	else									\
+		tput setaf  9; printf "[FAILING]";	\
+	fi;
+	@tput sgr 0; tput setaf 0;
+	@printf " $2";
+	@if [ $1 != 0 ]; then				\
+		printf " => test/$2.diff";		\
+	fi;
+	@tput sgr 0; printf "\n";
+endef
+
 test/%: test/%.tmp
-	@diff -u $@.out $@.tmp > $@.diff					\
-		&& echo $(LABEL_PASS) "$(notdir $@)""\033[1;0m"	\
-		&& rm $@.diff									\
-		|| echo $(LABEL_FAIL) "$(notdir $@) -> $@.diff""\033[1;0m"
+	$(eval CODE=$(shell diff -u $@.out $@.tmp > $@.diff && rm $@.diff; echo $$?))
+	$(call test_report,$(CODE),$(notdir $@))
 	@rm $@.tmp
