Makefile: changes made to comply with POSIX

diff --git a/test/Makefile b/test/Makefile
--- a/test/Makefile
+++ b/test/Makefile
@@ -1,48 +1,25 @@
 test: $(patsubst %.in,%,$(wildcard test/*.in))
 
-define exec_return_code:
-	$1 < $2 1> $3; printf $$?
-endef
+MSG_ERUN:=$E0;1;91mRuntime Error: $E0;90m
+SED_CMD :=sed -E 's/\.[0-9]+$$//g'
 
 tmp/%.out: test/%.in
 	@mkdir -p tmp
-	$(eval									\
-		EXEC=$(shell						\
-			echo "$(notdir $(@:.out=))" |	\
-			sed -E 's/\.[0-9]+$$//g'		\
-		)									\
-	)
-	$(eval EXEC=$(BUILD)/$(strip $(EXEC)))
-	@BUILD="$(BUILD)" CFLAGS="$(CFLAGS)" ENSURE="$(EXEC)" \
-	make ensure
-	@CODE=$$($(EXEC) < $< 1> $@; echo $$?);		\
-	if [ $${CODE} != "0" ]; then				\
-		tput sgr0; tput bold; tput setaf 9;		\
-		printf "Runtime Error During Test: "	\
-		tput sgr0; tput smul; tput setaf 8;		\
-		echo "$(EXEC) < $< 1> $@";				\
-		tput sgr0;								\
-	fi;
+	$(eval EXEC:=$(notdir $(@:.out=)))
+	$(eval EXEC:=$(shell echo $(EXEC) | $(SED_CMD)))
+	$(eval EXEC:=$(BUILD)/$(EXEC))
+	$(eval TEST:=$(EXEC) < $< 1> $@)
+	@	BUILD="$(BUILD)" CFLAGS="$(CFLAGS)"			\
+		ENSURE="$(EXEC)"							\
+		make ensure --no-print-directory
+	@	$(TEST)										\
+	||	(echo "$(MSG_ERUN)$(TEST)"; tput sgr0)
 
-LABEL_PASS="\033[1;32m[PASSING]\033[1;0m\033[1;2m"
-LABEL_FAIL="\033[1;31m[FAILING]\033[1;0m\033[1;2m"
-
-define test_report
-	@tput sgr0; tput bold;
-	@if [ $1 == 0 ]; then					\
-		tput setaf 10; printf "[PASSING]";	\
-	else									\
-		tput setaf  9; printf "[FAILING]";	\
-	fi;
-	@tput sgr0; tput setaf 0;
-	@printf " $2";
-	@if [ $1 != 0 ]; then				\
-		printf " => test/$2.diff";		\
-	fi;
-	@tput sgr0; printf "\n";
-endef
+MSG_PASS:=$E0;1;92m[PASSING]$E0;90m
+MSG_FAIL:=$E0;1;91m[FAILING]$E0;90m
 
 test/%: tmp/%.out
-	$(eval CODE=$(shell diff -u $@.out $< > $@.diff && rm $@.diff; echo $$?))
-	$(call test_report,$(CODE),$(notdir $@))
-	@rm $<
+	@	diff -u $@.out $< > $@.diff && rm $@.diff	\
+	&&	echo "$(MSG_PASS) $(notdir $@)"				\
+	||	echo "$(MSG_FAIL) $(notdir $@) -> $@.diff"
+	@	tput sgr0; rm $<
